//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v1.4.2 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------


import Component from 'reactxx-mui-web/ButtonBase/TouchRipple'

export * from 'reactxx-mui-web/ButtonBase/TouchRipple'
export default Component
