//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import PropTypes from 'prop-types';
import withStylesCreator from 'reactxx-mui-web/styles/withStyles';

const styles = theme => ({
  root: { ...theme.typography.button,
    backgroundColor: theme.palette.common.white,
    padding: theme.spacing.unit
  }
});

function TypographyTheme(props) {
  return <div className={props.classes.root}>{"This div's text looks like that of a button."}</div>;
}

TypographyTheme['propTypes'] = {
  classes: PropTypes.object.isRequired
};
export default withStylesCreator((styles as any), TypographyTheme)();