//autogenerated--------------------------------------------------------------------
//
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
//
//----------------------------------------------------------------------------------

import React from "react";
import PropTypes from "prop-types";
import { classNames } from "reactxx-basic";
import withStyles from "../styles/withStyles";
export const styles = {
  /* Styles applied to the root element. */
  root: {
    display: "table-footer-group"
  }
};

class TableFooter extends React.Component {
  getChildContext() {
    // eslint-disable-line class-methods-use-this
    return {
      tablelvl2: {
        variant: "footer"
      }
    };
  }

  render() {
    const {
      $system: { theme },
      classes,
      className,
      component: Component,
      ...other
    } = this.props;
    return (
      <Component className={classNames(classes.root, className)} {...other} />
    );
  }
}

TableFooter.childContextTypes = {
  tablelvl2: PropTypes.object
};
export const defaultProps = (TableFooter.defaultProps = {
  component: "tfoot"
});

export const TableFooterCode = TableFooter;
export const TableFooterCreator = withStyles(styles, TableFooter, {
  isMui: true,
  defaultProps
});
export const TableFooterComponent = TableFooterCreator();
if (TableFooter.muiName) TableFooterComponent.muiName = TableFooter.muiName;
export default TableFooterComponent;
