//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import PropTypes from 'prop-types';
import withStylesCreator from 'reactxx-mui-web/styles/withStyles';
import Switch from 'reactxx-mui-web/Switch/Switch';
import Paper from 'reactxx-mui-web/Paper/Paper';
import Collapse from 'reactxx-mui-web/Collapse/Collapse';

const styles = theme => ({
  root: {
    height: 180
  },
  container: {
    display: 'flex'
  },
  paper: {
    margin: theme.spacing.unit
  },
  svg: {
    width: 100,
    height: 100
  },
  polygon: {
    fill: theme.palette.common.white,
    stroke: theme.palette.divider,
    strokeWidth: 1
  }
});

class SimpleCollapse extends React.Component<any, any> {
  state: any = {
    checked: false
  };
  handleChange = () => {
    this.setState(state => ({
      checked: !state.checked
    }));
  };

  render() {
    const {
      classes
    } = this.props;
    const {
      checked
    } = this.state;
    return <div className={classes.root}>
        <Switch checked={checked} onChange={this.handleChange} aria-label="Collapse" />
        <div className={classes.container}>
          <Collapse in={checked}>
            <Paper elevation={4} className={classes.paper}>
              <svg className={classes.svg}>
                <polygon points="0,100 50,00, 100,100" className={classes.polygon} />
              </svg>
            </Paper>
          </Collapse>
          <Collapse in={checked} collapsedHeight="40px">
            <Paper elevation={4} className={classes.paper}>
              <svg className={classes.svg}>
                <polygon points="0,100 50,00, 100,100" className={classes.polygon} />
              </svg>
            </Paper>
          </Collapse>
        </div>
      </div>;
  }

}

SimpleCollapse['propTypes'] = {
  classes: PropTypes.object.isRequired
};
export default withStylesCreator((styles as any), SimpleCollapse)();