//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------


const code = `

# Portal

### The portal component renders its children into a new "subtree" outside of current component hierarchy.

The children of the portal component will be appended to the \`container\` specified.

The component is used internally by the [\`Modal\`](/utils/modal) and [\`Popper\`](/utils/popper) components.
On the server, the content won't be rendered.
You have to wait for the client side reconciliation to see the children.

## Simple Portal

!ReactxxDocExample[portal/SimplePortal]
`
export default code
    