//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

// @inheritedComponent FormControl
import React from "react";
import warning from "warning";
import PropTypes from "prop-types";
import Input from "../Input/Input";
import InputLabel from "../InputLabel/InputLabel";
import FormControl from "../FormControl/FormControl";
import FormHelperText from "../FormHelperText/FormHelperText";
import Select from "../Select/Select";
import { StandardProps, PropTypes as muiPropTypes } from "..";
import { FormControlProps } from "../FormControl/FormControl";
import { FormHelperTextProps } from "../FormHelperText/FormHelperText";
import { InputProps } from "../Input/Input";
import { InputLabelProps } from "../InputLabel/InputLabel";
import { FormControlClassKey } from "../FormControl/FormControl";
import { SelectProps } from "../Select/Select";
export interface TextFieldProps
  extends StandardProps<
      FormControlProps,
      TextFieldClassKey,
      "onChange" | "defaultValue"
    > {
  autoComplete?: string;
  autoFocus?: boolean;
  children?: React.ReactNode;
  defaultValue?: string | number;
  disabled?: boolean;
  error?: boolean;
  FormHelperTextProps?: Partial<FormHelperTextProps>;
  fullWidth?: boolean;
  helperText?: React.ReactNode;
  id?: string;
  InputLabelProps?: Partial<InputLabelProps>;
  InputProps?: Partial<InputProps>;
  inputProps?: InputProps["inputProps"];
  inputRef?: React.Ref<any> | React.RefObject<any>;
  label?: React.ReactNode;
  margin?: muiPropTypes.Margin;
  multiline?: boolean;
  name?: string;
  onChange?: React.ChangeEventHandler<
    HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
  >;
  placeholder?: string;
  required?: boolean;
  rows?: string | number;
  rowsMax?: string | number;
  select?: boolean;
  SelectProps?: Partial<SelectProps>;
  type?: string;
  value?: Array<string | number> | string | number;
}
export type TextFieldClassKey = FormControlClassKey;
/**
 * The `TextField` is a convenience wrapper for the most common cases (80%).
 * It cannot be all things to all people, otherwise the API would grow out of control.
 *
 * ## Advanced Configuration
 *
 * It's important to understand that the text field is a simple abstraction
 * on top of the following components:
 * - [FormControl](/api/form-control)
 * - [InputLabel](/api/input-label)
 * - [Input](/api/input)
 * - [FormHelperText](/api/form-helper-text)
 *
 * If you wish to alter the properties applied to the native input, you can do so as follows:
 *
 * ```jsx
 * const inputProps = {
 *   step: 300,
 * };
 *
 * return <TextField id="time" type="time" inputProps={inputProps} />;
 * ```
 *
 * For advanced cases, please look at the source of TextField by clicking on the
 * "Edit this page" button above. Consider either:
 * - using the upper case props for passing values directly to the components
 * - using the underlying components directly as shown in the demos
 */

const TextField: React.SFC<TextFieldProps> & {
  muiName?: string;
} = props => {
  const {
    autoComplete,
    autoFocus,
    children,
    className,
    defaultValue,
    disabled,
    error,
    FormHelperTextProps,
    fullWidth,
    helperText,
    id,
    InputLabelProps,
    inputProps,
    InputProps,
    inputRef,
    label,
    multiline,
    name,
    onBlur,
    onChange,
    onFocus,
    placeholder,
    required,
    rows,
    rowsMax,
    select,
    SelectProps,
    type,
    value,
    ...other
  } = props;
  warning(
    !select || Boolean(children),
    "Material-UI: `children` must be passed when using the `TextField` component with `select`."
  );
  const helperTextId = helperText && id ? `${id}-helper-text` : undefined;
  const InputElement = (
    <Input
      autoComplete={autoComplete}
      autoFocus={autoFocus}
      defaultValue={defaultValue as any}
      disabled={disabled}
      fullWidth={fullWidth}
      multiline={multiline}
      name={name}
      rows={rows}
      rowsMax={rowsMax}
      type={type}
      value={value}
      id={id}
      inputRef={inputRef}
      onBlur={onBlur}
      onChange={onChange}
      onFocus={onFocus}
      placeholder={placeholder}
      inputProps={inputProps}
      {...InputProps as any}
    />
  );
  return (
    <FormControl
      aria-describedby={helperTextId}
      className={className}
      error={error}
      fullWidth={fullWidth}
      required={required}
      {...other as any}
    >
      {label && (
        <InputLabel htmlFor={id} {...InputLabelProps as any}>
          {label}
        </InputLabel>
      )}
      {select ? (
        <Select value={value} input={InputElement} {...SelectProps as any}>
          {children}
        </Select>
      ) : (
        InputElement
      )}
      {helperText && (
        <FormHelperText id={helperTextId} {...FormHelperTextProps as any}>
          {helperText}
        </FormHelperText>
      )}
    </FormControl>
  );
};

TextField.defaultProps = {
  required: false,
  select: false
};
export default TextField;
