//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import { TCommon, Types, TProvider, WithStyleCreator as TWithStyleCreator } from 'reactxx-basic';
import withStyles, { Theme, toAtomic } from '../styles/withStyles';
import React from "react";
import PropTypes from "prop-types";
import { classNames } from "reactxx-basic";
import { capitalize } from "../utils/helpers";
import SwitchBase from "../internal/SwitchBase";
import { StandardProps } from "..";
import { SwitchBaseProps, SwitchBaseClassKey } from "../internal/SwitchBase";
export interface SwitchProps
  extends StandardProps<
      SwitchBaseProps,
      SwitchClassKey,
      "checkedIcon" | "color" | "icon"
    > {
  checkedIcon?: React.ReactNode;
  color?: "primary" | "secondary" | "default";
  icon?: React.ReactNode;
}
export type SwitchClassKey =
  | SwitchBaseClassKey
  | "bar"
  | "icon"
  | "iconChecked"
  | "switchBase"
  | "colorPrimary"
  | "colorSecondary";

const styles = theme => ({
  /* Styles applied to the root element. */
  root: {
    display: "inline-flex",
    width: 62,
    position: "relative",
    flexShrink: 0,
    // For correct alignment with the text.
    verticalAlign: "middle"
  },

  /* Styles used to create the `icon` passed to the internal `SwitchBase` component `icon` prop. */
  icon: {
    boxShadow: theme.shadows[1],
    backgroundColor: "currentColor",
    width: 20,
    height: 20,
    borderRadius: "50%",
    NAME$icon83: true
  },

  /* Styles applied the icon element component if `checked={true}`. */
  iconChecked: {
    boxShadow: theme.shadows[2]
  },

  /* Styles applied to the internal `SwitchBase` component's `root` class. */
  switchBase: {
    zIndex: 1,
    color:
      theme.palette.type === "light"
        ? theme.palette.grey[50]
        : theme.palette.grey[400],
    transition: theme.transitions.create("transform", {
      duration: theme.transitions.duration.shortest
    }),
    NAME$switchBase83: true
  },

  /* Styles applied to the internal `SwitchBase` component's `checked` class. */
  checked: {
    transform: "translateX(14px)",
    "& + .bar83": {
      opacity: 0.5
    },
    NAME$checked83: true
  },

  /* Styles applied to the internal SwitchBase component's root element if `color="primary"`. */
  colorPrimary: {
    "&.checked83": {
      color: theme.palette.primary.main,
      "& + .bar83": {
        backgroundColor: theme.palette.primary.main
      }
    }
  },

  /* Styles applied to the internal SwitchBase component's root element if `color="secondary"`. */
  colorSecondary: {
    "&.checked83": {
      color: theme.palette.secondary.main,
      "& + .bar83": {
        backgroundColor: theme.palette.secondary.main
      }
    }
  },

  /* Styles applied to the internal SwitchBase component's disabled class. */
  disabled: {
    "& + .bar83": {
      opacity: theme.palette.type === "light" ? 0.12 : 0.1
    },
    "& .icon83": {
      boxShadow: theme.shadows[1]
    },
    "&.switchBase83": {
      color:
        theme.palette.type === "light"
          ? theme.palette.grey[400]
          : theme.palette.grey[800],
      "& + .bar83": {
        backgroundColor:
          theme.palette.type === "light"
            ? theme.palette.common.black
            : theme.palette.common.white
      }
    }
  },

  /* Styles applied to the bar element. */
  bar: {
    borderRadius: 14 / 2,
    display: "block",
    position: "absolute",
    width: 34,
    height: 14,
    top: "50%",
    left: "50%",
    marginTop: -7,
    marginLeft: -17,
    transition: theme.transitions.create(["opacity", "background-color"], {
      duration: theme.transitions.duration.shortest
    }),
    backgroundColor:
      theme.palette.type === "light"
        ? theme.palette.common.black
        : theme.palette.common.white,
    opacity: theme.palette.type === "light" ? 0.38 : 0.3,
    NAME$bar83: true
  }
});

const Switch: Types.CodeSFCWeb<Shape> & {
  muiName?: string;
} = props => {
  const { classes, className, color, ...other } = props;
  return (
    <span className={classNames(classes.root, className)}>
      <SwitchBase
        type="checkbox"
        icon={<span className={classes.icon} />}
        classes={{
          root: classNames(
            classes.switchBase,
            classes[`color${capitalize(color)}`]
          ),
          checked: classes.checked,
          disabled: classes.disabled
        }}
        checkedIcon={
          <span className={classNames(classes.icon, classes.iconChecked)} />
        }
        {...other as any}
      />
      <span className={classes.bar} />
    </span>
  );
};

export interface Shape extends Types.ShapeDefault {
  common: TCommon.ShapeTexts<SwitchClassKey>,
  props: SwitchProps
  style: 'Text'
  theme: Theme
}
export type ComponentType = React.ComponentClass<Types.PropsX<Shape>> & TProvider<Shape>
export type CodeComponentType = Types.CodeComponentType<Shape>
export type SheetCreatorX = Types.SheetCreatorX<Shape>
export type PropsX = Types.PropsX<Shape>
export type CodeProps = Types.CodePropsWeb<Shape>
export type WithStyleCreator = TWithStyleCreator<Shape>

export const defaultProps  = Switch.defaultProps = {
  color: 'secondary'
} as CodeProps;
export const SwitchCode: CodeComponentType = Switch as any
export const SwitchStyles: SheetCreatorX = styles as any
export const SwitchCreator: WithStyleCreator = withStyles<Shape>(SwitchStyles, SwitchCode, {isMui:true, defaultProps});
export const SwitchComponent: React.ComponentType<PropsX> = SwitchCreator();
if ((Switch as any).muiName) (SwitchComponent as any).muiName = (Switch as any).muiName;


export default SwitchComponent
