//autogenerated--------------------------------------------------------------------
//
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
//
//----------------------------------------------------------------------------------

function ownerDocument(node) {
  return (node && node.ownerDocument) || document;
}

export default ownerDocument;
