//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import PropTypes from 'prop-types';
import withStylesCreator from 'reactxx-mui-web/styles/withStyles';
import Typography from 'reactxx-mui-web/Typography/Typography';
import Button from 'reactxx-mui-web/Button/Button';
import Popover from 'reactxx-mui-web/Popover/Popover';

const styles = theme => ({
  typography: {
    margin: theme.spacing.unit * 2
  }
});

class SimplePopover extends React.Component<any, any> {
  state: any = {
    anchorEl: null
  };
  handleClick = event => {
    this.setState({
      anchorEl: event.currentTarget
    });
  };
  handleClose = () => {
    this.setState({
      anchorEl: null
    });
  };

  render() {
    const {
      classes
    } = this.props;
    const {
      anchorEl
    } = this.state;
    const open = Boolean(anchorEl);
    return <div>
        <Button aria-owns={open ? 'simple-popper' : null} aria-haspopup="true" variant="contained" onClick={this.handleClick}>
          Open Popover
        </Button>
        <Popover id="simple-popper" open={open} anchorEl={anchorEl} onClose={this.handleClose} anchorOrigin={{
        vertical: 'bottom',
        horizontal: 'center'
      }} transformOrigin={{
        vertical: 'top',
        horizontal: 'center'
      }}>
          <Typography className={classes.typography}>The content of the Popover.</Typography>
        </Popover>
      </div>;
  }

}

SimplePopover['propTypes'] = {
  classes: PropTypes.object.isRequired
};
export default withStylesCreator((styles as any), SimplePopover)();