//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------


const code = `

# Lists

### Lists are continuous, vertical indexes of text or images.

[Lists](https://material.io/design/components/lists.html) are a continuous group of text or images. They are composed of items containing primary and supplemental actions, which are represented by icons and text.

## Simple List

!ReactxxDocExample[lists/SimpleList]

## Folder List

!ReactxxDocExample[lists/FolderList]

## Inset List

!ReactxxDocExample[lists/InsetList]

## Nested List

!ReactxxDocExample[lists/NestedList]

## Selected ListItem

!ReactxxDocExample[lists/SelectedListItem]

## Pinned Subheader List

Upon scrolling, subheaders remain pinned to the top of the screen until pushed off screen by the next subheader.

This feature is relying on the CSS sticky positioning.
Unfortunately it's [not implemented](https://caniuse.com/#search=sticky) by all the browsers we are supporting. We default to \`disableSticky\` when not supported.

!ReactxxDocExample[lists/PinnedSubheaderList]

## List Controls

### Checkbox

A checkbox can either be a primary action or a secondary action.

The checkbox is the primary action and the state indicator for the list item. The comment button is a secondary action and a separate target.

!ReactxxDocExample[lists/CheckboxList]

The checkbox is the secondary action for the list item and a separate target.

!ReactxxDocExample[lists/CheckboxListSecondary]

### Switch

The switch is the secondary action and a separate target.

!ReactxxDocExample[lists/SwitchListSecondary]

## Interactive

Below is an interactive demo that lets you explore the visual results of the different settings:

!ReactxxDocExample[lists/InteractiveList]
`
export default code
    