//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------


const code = `

# Selection Controls

### Selection controls allow the user to select options.

[Selection controls](https://material.io/design/components/selection-controls.html) allow users to complete tasks that involve making choices such as selecting options, or switching settings on or off. Selection controls are found on screens that ask users to make decisions or declare preferences such as settings or dialogs.

Three types of selection controls are covered in this section:

- **[Checkboxes](#checkboxes)** allow the selection of multiple options from a set.
- **[Radio Buttons](#radio-buttons)** allow the selection of a single option from a set.
- **[Switches](#switches)** allow a selection to be turned on or off.

## Checkboxes

[Checkboxes](https://material.io/design/components/selection-controls.html#checkboxes)
allow the user to select one or more items from a set.
Checkboxes can be used to turn an option on or off.

If you have multiple options appearing in a list,
you can preserve space by using checkboxes instead of on/off switches.
If you have a single option, avoid using a checkbox and use an on/off switch instead.

!ReactxxDocExample[selection-controls/Checkboxes]

\`Checkbox\` can also be used with a label description thanks to the \`FormControlLabel\` component.

!ReactxxDocExample[selection-controls/CheckboxLabels]

## Checkboxes with FormGroup

\`FormGroup\` is a helpful wrapper used to group selection controls components that provides an easier API.

!ReactxxDocExample[selection-controls/CheckboxesGroup]

## Radio Buttons

[Radio buttons](https://material.io/design/components/selection-controls.html#radio-buttons)
allow the user to select one option from a set.
Use radio buttons when the user needs to see all available options.
If available options can be collapsed, consider using a dropdown menu because it uses less space.

Radio buttons should have the most commonly used option selected by default.

\`RadioGroup\` is a helpful wrapper used to group \`Radio\` components that provides an easier API, and proper keyboard accessibility to the group.

!ReactxxDocExample[selection-controls/RadioButtonsGroup]

### Standalone Radio Buttons

\`Radio\` can also be used standalone, without the wrapper.

!ReactxxDocExample[selection-controls/RadioButtons]

## Switches

[Switches](https://material.io/design/components/selection-controls.html#switches)
toggle the state of a single setting on or off.
They are the preferred way to adjust settings on mobile.

The option that the switch controls, as well as the state it’s in,
should be made clear from the corresponding inline label.

!ReactxxDocExample[selection-controls/Switches]

### Switches with FormControlLabel
\`Switch\` can also be used with a label description thanks to the \`FormControlLabel\` component.

!ReactxxDocExample[selection-controls/SwitchLabels]

### Switches with FormGroup

\`FormGroup\` is a helpful wrapper used to group selection controls components that provides an easier API.
However, we encourage you to use a [Checkbox](#checkboxes) instead.

!ReactxxDocExample[selection-controls/SwitchesGroup]

### Customized Switches

If you have been reading the [overrides documentation page](/customization/overrides)
but you are not confident jumping in, here's an example of how you can change the color of a Switch, and an iOS style Switch.

!ReactxxDocExample[selection-controls/CustomizedSwitches]
`
export default code
    