//https://babeljs.io/docs/en/next/babel-generator
//https://babeljs.io/docs/en/next/babel-parser.html

//https://nodejs.org/api/fs.html

//https://github.com/isaacs/node-glob

//https://github.com/rse/astq
const driver = 'd:/'
const reactxx = driver + 'reactxx/muix/'
export const MUI_VERSION = 'v1.5.0'

export let isDoc = false
export const setIsDoc = (_isDoc:boolean) => {
    isDoc = _isDoc
    muiWeb = reactxx + (isDoc ? 'src/ks/common/muix-doc/' : 'src/mui-web/')
    patchOriginal = codemod + (isDoc ? 'patch-doc-original/' : 'patch-original/')
}

export let muiWeb = reactxx + (isDoc ? 'src/ks/common/muix-doc/' : 'src/mui-web/')
//export const muiWeb_Typings = muiWeb + 'typings/'

export const muix = reactxx + 'src/muix/'
export const muix_WebSources = muix + 'reactxx-mui-web/'
export const muix_Web = muix + 'current/'
//export const reactxxMuiWebComps = basicReactXX + 'src/muix/web/'

const codemod = driver + 'reactxx/codemod/'
//export const patchPrepare = codemod + 'patch-prepare/'
export let patchOriginal = codemod + (isDoc ? 'patch-doc-original/' : 'patch-original/')

//export const tempDump = driver + 'temp/dump/'

export const msgAutoGeneratedStart = '//autogenerated'
export const msgAutoGenerated =
`${msgAutoGeneratedStart}--------------------------------------------------------------------
// 
// This code was generated from material-ui ${MUI_VERSION} by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

`
