//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import Button from 'reactxx-mui-web/Button/Button';
import TextField from 'reactxx-mui-web/TextField/TextField';
import Dialog from 'reactxx-mui-web/Dialog/Dialog';
import DialogActions from 'reactxx-mui-web/DialogActions/DialogActions';
import DialogContent from 'reactxx-mui-web/DialogContent/DialogContent';
import DialogContentText from 'reactxx-mui-web/DialogContentText/DialogContentText';
import DialogTitle from 'reactxx-mui-web/DialogTitle/DialogTitle';

export default class FormDialog extends React.Component<any,any> {
  state: any = {
    open: false,
  };

  handleClickOpen = () => {
    this.setState({ open: true });
  };

  handleClose = () => {
    this.setState({ open: false });
  };

  render() {
    return (
      <div>
        <Button onClick={this.handleClickOpen}>Open form dialog</Button>
        <Dialog
          open={this.state.open}
          onClose={this.handleClose}
          aria-labelledby="form-dialog-title"
        >
          <DialogTitle id="form-dialog-title">Subscribe</DialogTitle>
          <DialogContent>
            <DialogContentText>
              To subscribe to this website, please enter your email address here. We will send
              updates occasionally.
            </DialogContentText>
            <TextField
              autoFocus
              margin="dense"
              id="name"
              label="Email Address"
              type="email"
              fullWidth
            />
          </DialogContent>
          <DialogActions>
            <Button onClick={this.handleClose} color="primary">
              Cancel
            </Button>
            <Button onClick={this.handleClose} color="primary">
              Subscribe
            </Button>
          </DialogActions>
        </Dialog>
      </div>
    );
  }
}
