export { default as View } from './View/View'
export { default as Text } from './Text/Text'
export { default as ScrollView } from './ScrollView/ScrollView'
export { default as Typography } from './Typography/Typography'
export { Shape as TypographyShape } from '../common/Typography/Typography'
export { default as Icon } from './Icon/Icon'
export { iconColor, iconSize } from '../common/Icon/Icon' 