//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import PropTypes from 'prop-types';
import withStylesCreator from 'reactxx-mui-web/styles/withStyles';
import pink from 'reactxx-mui-web/colors/pink';
import green from 'reactxx-mui-web/colors/green';
import Avatar from 'reactxx-mui-web/Avatar/Avatar';
import FolderIcon from 'reactxx-icons/Folder';
import PageviewIcon from 'reactxx-icons/Pageview';
import AssignmentIcon from 'reactxx-icons/Assignment';
const styles = {
  avatar: {
    margin: 10
  },
  pinkAvatar: {
    margin: 10,
    color: '#fff',
    backgroundColor: pink[500]
  },
  greenAvatar: {
    margin: 10,
    color: '#fff',
    backgroundColor: green[500]
  },
  row: {
    display: 'flex',
    justifyContent: 'center'
  }
};

function IconAvatars(props) {
  const {
    classes
  } = props;
  return <div className={classes.row}>
      <Avatar className={classes.avatar}>
        <FolderIcon />
      </Avatar>
      <Avatar className={classes.pinkAvatar}>
        <PageviewIcon />
      </Avatar>
      <Avatar className={classes.greenAvatar}>
        <AssignmentIcon />
      </Avatar>
    </div>;
}

IconAvatars['propTypes'] = {
  classes: PropTypes.object.isRequired
};
export default withStylesCreator((styles as any), IconAvatars)();