//autogenerated--------------------------------------------------------------------
//
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
//
//----------------------------------------------------------------------------------

import React from "react";
import { toAtomic } from "../styles/withStyles";

import PropTypes from "prop-types";
import { classNames } from "reactxx-basic";
import withStyles from "../styles/withStyles";
export const styles = {
  /* Styles applied to the root element. */
  root: {
    ...toAtomic("padding", "8px 24px 24px"),
    display: "flex"
  }
};

function ExpansionPanelDetails(props) {
  const {
    $system: { theme },
    classes,
    children,
    className,
    ...other
  } = props;
  return (
    <div className={classNames(classes.root, className)} {...other}>
      {children}
    </div>
  );
}

export const defaultProps = (ExpansionPanelDetails.defaultProps = {});

export const ExpansionPanelDetailsCode = ExpansionPanelDetails;
export const ExpansionPanelDetailsCreator = withStyles(
  styles,
  ExpansionPanelDetails,
  {
    isMui: true,
    defaultProps
  }
);
export const ExpansionPanelDetailsComponent = ExpansionPanelDetailsCreator();
if (ExpansionPanelDetails.muiName)
  ExpansionPanelDetailsComponent.muiName = ExpansionPanelDetails.muiName;
export default ExpansionPanelDetailsComponent;
