//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import { TCommon, Types, TProvider, WithStyleCreator as TWithStyleCreator } from 'reactxx-basic';
import withStyles, { Theme } from '../styles/withStyles';
import React from "react";
import { classNames } from "reactxx-basic";
import { StandardProps } from "..";
export interface ExpansionPanelDetailsProps
  extends StandardProps<
      React.HTMLAttributes<HTMLDivElement>,
      ExpansionPanelDetailsClassKey
    > {}
export type ExpansionPanelDetailsClassKey = "root";
const styles = {
  /* Styles applied to the root element. */
  root: {
    display: "flex",
    padding: "8px 24px 24px"
  }
};

const ExpansionPanelDetails: Types.CodeSFCWeb<Shape> = props => {
  const { classes, children, className, ...other } = props;
  return (
    <div className={classNames(classes.root, className)} {...other}>
      {children}
    </div>
  );
};

export type Shape = Types.OverwriteShape<{
  common: TCommon.ShapeTexts<ExpansionPanelDetailsClassKey>,
  props: ExpansionPanelDetailsProps,
  theme: Theme
}>
export type ComponentType = React.ComponentClass<Types.PropsX<Shape>> & TProvider<Shape>
export type CodeComponentType = Types.CodeComponentType<Shape>
export type SheetCreatorX = Types.SheetCreatorX<Shape>
export type PropsX = Types.PropsX<Shape>
export type CodeProps = Types.CodePropsWeb<Shape>
export type WithStyleCreator = TWithStyleCreator<Shape>

export const defaultProps  = ExpansionPanelDetails.defaultProps = {} as CodeProps;
export const ExpansionPanelDetailsCode: CodeComponentType = ExpansionPanelDetails as any
export const ExpansionPanelDetailsStyles: SheetCreatorX = styles as any
export const ExpansionPanelDetailsCreator: WithStyleCreator = withStyles<Shape>(ExpansionPanelDetailsStyles, ExpansionPanelDetailsCode, {isMui:true, defaultProps});
export const ExpansionPanelDetailsComponent: React.ComponentType<PropsX> = ExpansionPanelDetailsCreator();
if ((ExpansionPanelDetails as any).muiName) (ExpansionPanelDetailsComponent as any).muiName = (ExpansionPanelDetails as any).muiName;


export default ExpansionPanelDetails
