//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

// @inheritedComponent Input
import React from "react";
import PropTypes from "prop-types";
import SelectInput from "./SelectInput";
import mergeClasses from "../styles/mergeClasses";
import ArrowDropDownIcon from "../internal/svg-icons/ArrowDropDown";
import Input from "../Input/Input";
import { styles as nativeSelectStyles } from "../NativeSelect/NativeSelect";
import NativeSelectInput from "../NativeSelect/NativeSelectInput";
import { StandardProps } from "..";
import { InputProps } from "../Input/Input";
import { MenuProps } from "../Menu/Menu";
import { SelectInputProps } from "./SelectInput";
export interface SelectProps
  extends StandardProps<InputProps, SelectClassKey, "value" | "onChange">,
    Pick<SelectInputProps, "onChange"> {
  autoWidth?: boolean;
  displayEmpty?: boolean;
  IconComponent?: React.ReactType;
  input?: React.ReactNode;
  MenuProps?: Partial<MenuProps>;
  multiple?: boolean;
  native?: boolean;
  onClose?: (event: React.ChangeEvent<{}>) => void;
  onOpen?: (event: React.ChangeEvent<{}>) => void;
  open?: boolean;
  renderValue?: (value: SelectProps["value"]) => React.ReactNode;
  SelectDisplayProps?: React.HTMLAttributes<HTMLDivElement>;
  value?: Array<string | number | boolean> | string | number | boolean;
}
export type SelectClassKey =
  | "root"
  | "select"
  | "selectMenu"
  | "disabled"
  | "icon";
const styles = nativeSelectStyles;

const Select: Types.CodeSFCWeb<Shape> = props => {
  const {
    autoWidth,
    children,
    classes,
    displayEmpty,
    IconComponent,
    input,
    inputProps,
    MenuProps,
    multiple,
    native,
    onClose,
    onOpen,
    open,
    renderValue,
    SelectDisplayProps,
    ...other
  } = props;
  const inputComponent = native ? NativeSelectInput : SelectInput;
  return React.cloneElement(input, {
    // Most of the logic is implemented in `SelectInput`.
    // The `Select` component is a simple API wrapper to expose something better to play with.
    inputComponent,
    inputProps: {
      children,
      IconComponent,
      type: undefined,
      // We render a select. We can ignore the type provided by the `Input`.
      ...(native
        ? {}
        : {
            autoWidth,
            displayEmpty,
            MenuProps,
            multiple,
            onClose,
            onOpen,
            open,
            renderValue,
            SelectDisplayProps
          }),
      ...inputProps,
      classes: inputProps
        ? mergeClasses({
            baseClasses: classes,
            newClasses: inputProps.classes,
            Component: Select
          })
        : classes,
      ...(input ? input.props.inputProps : {})
    },
    ...other
  });
};

Select.defaultProps = {
  autoWidth: false,
  displayEmpty: false,
  IconComponent: ArrowDropDownIcon,
  input: <Input />,
  multiple: false,
  native: false
};
Select.muiName = "Select";
export default withStyles(nativeSelectStyles, {
  name: "MuiSelect"
})(Select);
