//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------


const code = `

# Tables

### Data tables display sets of data. They can be fully customized.

[Data tables](https://material.io/design/components/data-tables.html) display information in a way that’s easy to scan, so that users can look for patterns and insights. They can be embedded in primary content, such as cards.

Data tables can include:
- A corresponding visualization
- Navigation
- Tools to query and manipulate data

When including tools, they should be placed directly above or below the table.

## Structure

A data table contains a header row at the top that lists column names, followed by rows for data.

Checkboxes should accompany each row if the user needs to select or manipulate data.

For accessibility, the first column is set to be a \`<th>\` element, with a \`scope\` of \`"row"\`. This enables screen readers to identify a cell's value by it's row and column name.

## Simple Table

A simple example with no frills.

!ReactxxDocExample[tables/SimpleTable]

## Sorting & Selecting

This example demonstrates the use of \`Checkbox\` and clickable rows for selection, with a custom \`Toolbar\`. It uses the \`TableSortLabel\` component to help style column headings.

The Table has been given a fixed width to demonstrate horizontal scrolling. In order to prevent the pagination controls from scrolling, the TablePagination component is used outside of the Table. (The ['Custom Table Pagination Action' example](#custom-table-pagination-action) below shows the pagination within the TableFooter.)

!ReactxxDocExample[tables/EnhancedTable]

## Custom Table Pagination Action

The \`Action\` property of the \`TablePagination\` component allows the implementation of
custom actions.

!ReactxxDocExample[tables/CustomPaginationActionsTable]

## Customized Tables

You can customize the look and feel of the table by overriding the styles of the \`TableCell\` component.

!ReactxxDocExample[tables/CustomizedTable]
`
export default code
    