//autogenerated--------------------------------------------------------------------
//
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
//
//----------------------------------------------------------------------------------

const shape = {
  borderRadius: 4
};
export default shape;
export interface Shape {
  borderRadius: number;
}
export type ShapeOptions = Partial<Shape>;
