//autogenerated--------------------------------------------------------------------
//
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
//
//----------------------------------------------------------------------------------

import React from "react";
import { toAtomic } from "../styles/withStyles";

import PropTypes from "prop-types";
import { classNames } from "reactxx-basic";
import withStyles from "../styles/withStyles";
import { cloneChildrenWithClassName } from "../utils/reactHelpers";
import "../Button/Button"; // So we don't have any override priority issue.

export const styles = {
  /* Styles applied to the root element. */
  root: {
    ...toAtomic("padding", "16px 8px"),
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end"
  },

  /* Styles applied to the children. */
  action: {
    marginLeft: 8
  }
};

function ExpansionPanelActions(props) {
  const {
    $system: { theme },
    children,
    classes,
    className,
    ...other
  } = props;
  return (
    <div className={classNames(classes.root, className)} {...other}>
      {cloneChildrenWithClassName(children, classes.action)}
    </div>
  );
}

export const defaultProps = (ExpansionPanelActions.defaultProps = {});

export const ExpansionPanelActionsCode = ExpansionPanelActions;
export const ExpansionPanelActionsCreator = withStyles(
  styles,
  ExpansionPanelActions,
  {
    isMui: true,
    defaultProps
  }
);
export const ExpansionPanelActionsComponent = ExpansionPanelActionsCreator();
if (ExpansionPanelActions.muiName)
  ExpansionPanelActionsComponent.muiName = ExpansionPanelActions.muiName;
export default ExpansionPanelActionsComponent;
