//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

export interface Shape {
  borderRadius: number;
}
export type ShapeOptions = Partial<Shape>;
const shape = {
  borderRadius: 4
};
export default shape;
