//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import PropTypes from 'prop-types';
import Paper from 'reactxx-mui-web/Paper/Paper';
import withStylesCreator from 'reactxx-mui-web/styles/withStyles';
import Grid from 'reactxx-mui-web/Grid/Grid';
import Avatar from 'reactxx-mui-web/Avatar/Avatar';
import Typography from 'reactxx-mui-web/Typography/Typography';

const styles = theme => ({
  root: {
    overflow: 'hidden',
    padding: `0 ${theme.spacing.unit * 3}px`
  },
  wrapper: {
    maxWidth: 400
  },
  paper: {
    margin: theme.spacing.unit,
    padding: theme.spacing.unit * 2
  }
});

function AutoGridNoWrap(props) {
  const {
    classes
  } = props;
  const message = `Truncation should be conditionally applicable on this long line of text
                    as this is a much longer line than what the container can support. `;
  return <div className={classes.root}>
      <div className={classes.wrapper}>
        <Paper className={classes.paper}>
          <Grid container wrap="nowrap" spacing={16}>
            <Grid item>
              <Avatar>W</Avatar>
            </Grid>
            <Grid item xs zeroMinWidth>
              <Typography noWrap>{message}</Typography>
            </Grid>
          </Grid>
        </Paper>
        <Paper className={classes.paper}>
          <Grid container wrap="nowrap" spacing={16}>
            <Grid item>
              <Avatar>W</Avatar>
            </Grid>
            <Grid item xs>
              <Typography noWrap>{message}</Typography>
            </Grid>
          </Grid>
        </Paper>
        <Paper className={classes.paper}>
          <Grid container wrap="nowrap" spacing={16}>
            <Grid item>
              <Avatar>W</Avatar>
            </Grid>
            <Grid item xs>
              <Typography>{message}</Typography>
            </Grid>
          </Grid>
        </Paper>
      </div>
    </div>;
}

AutoGridNoWrap['propTypes'] = {
  classes: PropTypes.object.isRequired
};
export default withStylesCreator((styles as any), AutoGridNoWrap)();