import { AppBarClassKey } from 'reactxx-muix/typings/AppBar';
import { AvatarClassKey } from 'reactxx-muix/typings/Avatar';
import { BackdropClassKey } from 'reactxx-muix/typings/Backdrop';
import { BadgeClassKey } from 'reactxx-muix/typings/Badge';
import { BottomNavigationActionClassKey } from 'reactxx-muix/typings/BottomNavigationAction';
import { BottomNavigationClassKey } from 'reactxx-muix/typings/BottomNavigation';
import { ButtonBaseClassKey } from 'reactxx-muix/typings/ButtonBase';
import { ButtonClassKey } from 'reactxx-muix/typings/Button';
import { CardActionsClassKey } from 'reactxx-muix/typings/CardActions';
import { CardClassKey } from 'reactxx-muix/typings/Card';
import { CardContentClassKey } from 'reactxx-muix/typings/CardContent';
import { CardHeaderClassKey } from 'reactxx-muix/typings/CardHeader';
import { CardMediaClassKey } from 'reactxx-muix/typings/CardMedia';
import { CheckboxClassKey } from 'reactxx-muix/typings/Checkbox';
import { ChipClassKey } from 'reactxx-muix/typings/Chip';
import { CircularProgressClassKey } from 'reactxx-muix/typings/CircularProgress';
import { CollapseClassKey } from 'reactxx-muix/typings/Collapse';
import { CssBaselineClassKey } from 'reactxx-muix/typings/CssBaseline';
import { DialogActionsClassKey } from 'reactxx-muix/typings/DialogActions';
import { DialogClassKey } from 'reactxx-muix/typings/Dialog';
import { DialogContentClassKey } from 'reactxx-muix/typings/DialogContent';
import { DialogContentTextClassKey } from 'reactxx-muix/typings/DialogContentText';
import { DialogTitleClassKey } from 'reactxx-muix/typings/DialogTitle';
import { DividerClassKey } from 'reactxx-muix/typings/Divider';
import { DrawerClassKey } from 'reactxx-muix/typings/Drawer';
import { ExpansionPanelActionsClassKey } from 'reactxx-muix/typings/ExpansionPanelActions';
import { ExpansionPanelClassKey } from 'reactxx-muix/typings/ExpansionPanel';
import { ExpansionPanelDetailsClassKey } from 'reactxx-muix/typings/ExpansionPanelDetails';
import { ExpansionPanelSummaryClassKey } from 'reactxx-muix/typings/ExpansionPanelSummary';
import { FormControlClassKey } from 'reactxx-muix/typings/FormControl';
import { FormControlLabelClassKey } from 'reactxx-muix/typings/FormControlLabel';
import { FormGroupClassKey } from 'reactxx-muix/typings/FormGroup';
import { FormHelperTextClassKey } from 'reactxx-muix/typings/FormHelperText';
import { FormLabelClassKey } from 'reactxx-muix/typings/FormLabel';
import { GridClassKey } from 'reactxx-muix/typings/Grid';
import { GridListClassKey } from 'reactxx-muix/typings/GridList';
import { GridListTileBarClassKey } from 'reactxx-muix/typings/GridListTileBar';
import { GridListTileClassKey } from 'reactxx-muix/typings/GridListTile';
import { IconButtonClassKey } from 'reactxx-muix/typings/IconButton';
import { IconClassKey } from 'reactxx-muix/typings/Icon';
import { InputAdornmentClassKey } from 'reactxx-muix/typings/InputAdornment';
import { InputClassKey } from 'reactxx-muix/typings/Input';
import { InputLabelClassKey } from 'reactxx-muix/typings/InputLabel';
import { LinearProgressClassKey } from 'reactxx-muix/typings/LinearProgress';
import { ListClassKey } from 'reactxx-muix/typings/List';
import { ListItemAvatarClassKey } from 'reactxx-muix/typings/ListItemAvatar';
import { ListItemClassKey } from 'reactxx-muix/typings/ListItem';
import { ListItemIconClassKey } from 'reactxx-muix/typings/ListItemIcon';
import { ListItemSecondaryActionClassKey } from 'reactxx-muix/typings/ListItemSecondaryAction';
import { ListItemTextClassKey } from 'reactxx-muix/typings/ListItemText';
import { ListSubheaderClassKey } from 'reactxx-muix/typings/ListSubheader';
import { MenuClassKey } from 'reactxx-muix/typings/Menu';
import { MenuItemClassKey } from 'reactxx-muix/typings/MenuItem';
import { MenuListClassKey } from 'reactxx-muix/typings/MenuList';
import { MobileStepperClassKey } from 'reactxx-muix/typings/MobileStepper';
import { ModalClassKey } from 'reactxx-muix/typings/Modal';
import { NativeSelectClassKey } from 'reactxx-muix/typings/NativeSelect';
import { PaperClassKey } from 'reactxx-muix/typings/Paper';
import { PopoverClassKey } from 'reactxx-muix/typings/Popover';
import { RadioClassKey } from 'reactxx-muix/typings/Radio';
import { RadioGroupClassKey } from 'reactxx-muix/typings/RadioGroup';
import { SelectClassKey } from 'reactxx-muix/typings/Select';
import { SnackbarClassKey } from 'reactxx-muix/typings/Snackbar';
import { SnackbarContentClassKey } from 'reactxx-muix/typings/SnackbarContent';
import { StepButtonClasskey } from 'reactxx-muix/typings/StepButton';
import { StepClasskey } from 'reactxx-muix/typings/Step';
import { StepConnectorClasskey } from 'reactxx-muix/typings/StepConnector';
import { StepContentClasskey } from 'reactxx-muix/typings/StepContent';
import { StepIconClasskey } from 'reactxx-muix/typings/StepIcon';
import { StepLabelClasskey } from 'reactxx-muix/typings/StepLabel';
import { StepperClasskey } from 'reactxx-muix/typings/Stepper';
import { StyleRules } from 'reactxx-muix/typings/styles/withStyles';
import { SvgIconClassKey } from 'reactxx-muix/typings/SvgIcon';
import { SwitchBaseClassKey } from 'reactxx-muix/typings/internal/SwitchBase';
import { SwitchClassKey } from 'reactxx-muix/typings/Switch';
import { TabClassKey } from 'reactxx-muix/typings/Tab';
import { TableBodyClassKey } from 'reactxx-muix/typings/TableBody';
import { TableCellClassKey } from 'reactxx-muix/typings/TableCell';
import { TableClassKey } from 'reactxx-muix/typings/Table';
import { TableFooterClassKey } from 'reactxx-muix/typings/TableFooter';
import { TableHeadClassKey } from 'reactxx-muix/typings/TableHead';
import { TablePaginationClassKey } from 'reactxx-muix/typings/TablePagination';
import { TableRowClassKey } from 'reactxx-muix/typings/TableRow';
import { TableSortLabelClassKey } from 'reactxx-muix/typings/TableSortLabel';
import { TabsClassKey } from 'reactxx-muix/typings/Tabs';
import { ToolbarClassKey } from 'reactxx-muix/typings/Toolbar';
import { TooltipClassKey } from 'reactxx-muix/typings/Tooltip';
import { TouchRippleClassKey } from 'reactxx-muix/typings/ButtonBase/TouchRipple';
import { TypographyClassKey } from 'reactxx-muix/typings/Typography';

export type Overrides = {
  [Name in keyof ComponentNameToClassKey]?: Partial<StyleRules<ComponentNameToClassKey[Name]>>
};

type ComponentNameToClassKey = {
  MuiAppBar: AppBarClassKey;
  MuiAvatar: AvatarClassKey;
  MuiBackdrop: BackdropClassKey;
  MuiBadge: BadgeClassKey;
  MuiBottomNavigation: BottomNavigationClassKey;
  MuiBottomNavigationAction: BottomNavigationActionClassKey;
  MuiButton: ButtonClassKey;
  MuiButtonBase: ButtonBaseClassKey;
  MuiCard: CardClassKey;
  MuiCardActions: CardActionsClassKey;
  MuiCardContent: CardContentClassKey;
  MuiCardHeader: CardHeaderClassKey;
  MuiCardMedia: CardMediaClassKey;
  MuiCheckbox: CheckboxClassKey;
  MuiChip: ChipClassKey;
  MuiCircularProgress: CircularProgressClassKey;
  MuiCollapse: CollapseClassKey;
  MuiCssBaseline: CssBaselineClassKey;
  MuiDialog: DialogClassKey;
  MuiDialogActions: DialogActionsClassKey;
  MuiDialogContent: DialogContentClassKey;
  MuiDialogContentText: DialogContentTextClassKey;
  MuiDialogTitle: DialogTitleClassKey;
  MuiDivider: DividerClassKey;
  MuiDrawer: DrawerClassKey;
  MuiExpansionPanel: ExpansionPanelClassKey;
  MuiExpansionPanelActions: ExpansionPanelActionsClassKey;
  MuiExpansionPanelDetails: ExpansionPanelDetailsClassKey;
  MuiExpansionPanelSummary: ExpansionPanelSummaryClassKey;
  MuiFormControl: FormControlClassKey;
  MuiFormControlLabel: FormControlLabelClassKey;
  MuiFormGroup: FormGroupClassKey;
  MuiFormHelperText: FormHelperTextClassKey;
  MuiFormLabel: FormLabelClassKey;
  MuiGrid: GridClassKey;
  MuiGridList: GridListClassKey;
  MuiGridListTile: GridListTileClassKey;
  MuiGridListTileBar: GridListTileBarClassKey;
  MuiIcon: IconClassKey;
  MuiIconButton: IconButtonClassKey;
  MuiInput: InputClassKey;
  MuiInputAdornment: InputAdornmentClassKey;
  MuiInputLabel: InputLabelClassKey;
  MuiLinearProgress: LinearProgressClassKey;
  MuiList: ListClassKey;
  MuiListItem: ListItemClassKey;
  MuiListItemAvatar: ListItemAvatarClassKey;
  MuiListItemIcon: ListItemIconClassKey;
  MuiListItemSecondaryAction: ListItemSecondaryActionClassKey;
  MuiListItemText: ListItemTextClassKey;
  MuiListSubheader: ListSubheaderClassKey;
  MuiMenu: MenuClassKey;
  MuiMenuItem: MenuItemClassKey;
  MuiMobileStepper: MobileStepperClassKey;
  MuiModal: ModalClassKey;
  MuiNativeSelect: NativeSelectClassKey;
  MuiPaper: PaperClassKey;
  MuiPopover: PopoverClassKey;
  MuiRadio: RadioClassKey;
  MuiSelect: SelectClassKey;
  MuiSnackbar: SnackbarClassKey;
  MuiSnackbarContent: SnackbarContentClassKey;
  MuiStep: StepClasskey;
  MuiStepButton: StepButtonClasskey;
  MuiStepConnector: StepConnectorClasskey;
  MuiStepContent: StepContentClasskey;
  MuiStepIcon: StepIconClasskey;
  MuiStepLabel: StepLabelClasskey;
  MuiStepper: StepperClasskey;
  MuiSvgIcon: SvgIconClassKey;
  MuiSwitch: SwitchClassKey;
  MuiSwitchBase: SwitchBaseClassKey;
  MuiTab: TabClassKey;
  MuiTable: TableClassKey;
  MuiTableCell: TableCellClassKey;
  MuiTablePagination: TablePaginationClassKey;
  MuiTableRow: TableRowClassKey;
  MuiTableSortLabel: TableSortLabelClassKey;
  MuiTabs: TabsClassKey;
  MuiToolbar: ToolbarClassKey;
  MuiTooltip: TooltipClassKey;
  MuiTouchRipple: TouchRippleClassKey;
  MuiTypography: TypographyClassKey;
};
