import { AppBarProps } from 'reactxx-muix/typings/AppBar';
import { AvatarProps } from 'reactxx-muix/typings/Avatar';
import { BackdropProps } from 'reactxx-muix/typings/Backdrop';
import { BadgeProps } from 'reactxx-muix/typings/Badge';
import { BottomNavigationActionProps } from 'reactxx-muix/typings/BottomNavigationAction';
import { BottomNavigationProps } from 'reactxx-muix/typings/BottomNavigation';
import { ButtonBaseProps } from 'reactxx-muix/typings/ButtonBase';
import { ButtonProps } from 'reactxx-muix/typings/Button';
import { CardActionsProps } from 'reactxx-muix/typings/CardActions';
import { CardContentProps } from 'reactxx-muix/typings/CardContent';
import { CardHeaderProps } from 'reactxx-muix/typings/CardHeader';
import { CardMediaProps } from 'reactxx-muix/typings/CardMedia';
import { CardProps } from 'reactxx-muix/typings/Card';
import { CheckboxProps } from 'reactxx-muix/typings/Checkbox';
import { ChipProps } from 'reactxx-muix/typings/Chip';
import { CircularProgressProps } from 'reactxx-muix/typings/CircularProgress';
import { CollapseProps } from 'reactxx-muix/typings/Collapse';
import { CssBaselineProps } from 'reactxx-muix/typings/CssBaseline';
import { DialogActionsProps } from 'reactxx-muix/typings/DialogActions';
import { DialogContentProps } from 'reactxx-muix/typings/DialogContent';
import { DialogContentTextProps } from 'reactxx-muix/typings/DialogContentText';
import { DialogProps } from 'reactxx-muix/typings/Dialog';
import { DialogTitleProps } from 'reactxx-muix/typings/DialogTitle';
import { DividerProps } from 'reactxx-muix/typings/Divider';
import { DrawerProps } from 'reactxx-muix/typings/Drawer';
import { ExpansionPanelActionsProps } from 'reactxx-muix/typings/ExpansionPanelActions';
import { ExpansionPanelDetailsProps } from 'reactxx-muix/typings/ExpansionPanelDetails';
import { ExpansionPanelProps } from 'reactxx-muix/typings/ExpansionPanel';
import { ExpansionPanelSummaryProps } from 'reactxx-muix/typings/ExpansionPanelSummary';
import { FormControlLabelProps } from 'reactxx-muix/typings/FormControlLabel';
import { FormControlProps } from 'reactxx-muix/typings/FormControl';
import { FormGroupProps } from 'reactxx-muix/typings/FormGroup';
import { FormHelperTextProps } from 'reactxx-muix/typings/FormHelperText';
import { FormLabelProps } from 'reactxx-muix/typings/FormLabel';
import { GridListProps } from 'reactxx-muix/typings/GridList';
import { GridListTileBarProps } from 'reactxx-muix/typings/GridListTileBar';
import { GridListTileProps } from 'reactxx-muix/typings/GridListTile';
import { GridProps } from 'reactxx-muix/typings/Grid';
import { IconButtonProps } from 'reactxx-muix/typings/IconButton';
import { IconProps } from 'reactxx-muix/typings/Icon';
import { InputAdornmentProps } from 'reactxx-muix/typings/InputAdornment';
import { InputLabelProps } from 'reactxx-muix/typings/InputLabel';
import { InputProps } from 'reactxx-muix/typings/Input';
import { LinearProgressProps } from 'reactxx-muix/typings/LinearProgress';
import { ListItemAvatarProps } from 'reactxx-muix/typings/ListItemAvatar';
import { ListItemIconProps } from 'reactxx-muix/typings/ListItemIcon';
import { ListItemProps } from 'reactxx-muix/typings/ListItem';
import { ListItemSecondaryActionProps } from 'reactxx-muix/typings/ListItemSecondaryAction';
import { ListItemTextProps } from 'reactxx-muix/typings/ListItemText';
import { ListProps } from 'reactxx-muix/typings/List';
import { ListSubheaderProps } from 'reactxx-muix/typings/ListSubheader';
import { MenuItemProps } from 'reactxx-muix/typings/MenuItem';
import { MenuListProps } from 'reactxx-muix/typings/MenuList';
import { MenuProps } from 'reactxx-muix/typings/Menu';
import { MobileStepperProps } from 'reactxx-muix/typings/MobileStepper';
import { ModalProps } from 'reactxx-muix/typings/Modal';
import { NativeSelectProps } from 'reactxx-muix/typings/NativeSelect';
import { PaperProps } from 'reactxx-muix/typings/Paper';
import { PopoverProps } from 'reactxx-muix/typings/Popover';
import { RadioGroupProps } from 'reactxx-muix/typings/RadioGroup';
import { RadioProps } from 'reactxx-muix/typings/Radio';
import { SelectProps } from 'reactxx-muix/typings/Select';
import { SnackbarContentProps } from 'reactxx-muix/typings/SnackbarContent';
import { SnackbarProps } from 'reactxx-muix/typings/Snackbar';
import { StepButtonProps } from 'reactxx-muix/typings/StepButton';
import { StepConnectorProps } from 'reactxx-muix/typings/StepConnector';
import { StepContentProps } from 'reactxx-muix/typings/StepContent';
import { StepIconProps } from 'reactxx-muix/typings/StepIcon';
import { StepLabelProps } from 'reactxx-muix/typings/StepLabel';
import { StepperProps } from 'reactxx-muix/typings/Stepper';
import { StepProps } from 'reactxx-muix/typings/Step';
import { StyleRules } from 'reactxx-muix/typings/styles/withStyles';
import { SvgIconProps } from 'reactxx-muix/typings/SvgIcon';
import { SwitchBaseProps } from 'reactxx-muix/typings/internal/SwitchBase';
import { SwitchProps } from 'reactxx-muix/typings/Switch';
import { TableCellProps } from 'reactxx-muix/typings/TableCell';
import { TablePaginationProps } from 'reactxx-muix/typings/TablePagination';
import { TableProps } from 'reactxx-muix/typings/Table';
import { TableRowProps } from 'reactxx-muix/typings/TableRow';
import { TableSortLabelProps } from 'reactxx-muix/typings/TableSortLabel';
import { TabProps } from 'reactxx-muix/typings/Tab';
import { TabsProps } from 'reactxx-muix/typings/Tabs';
import { ToolbarProps } from 'reactxx-muix/typings/Toolbar';
import { TooltipProps } from 'reactxx-muix/typings/Tooltip';
import { TouchRippleProps } from 'reactxx-muix/typings/ButtonBase/TouchRipple';
import { TypographyProps } from 'reactxx-muix/typings/Typography';

export type ComponentsProps = {
  [Name in keyof ComponentsPropsList]?: Partial<ComponentsPropsList[Name]>
};

type ComponentsPropsList = {
  MuiAppBar: AppBarProps;
  MuiAvatar: AvatarProps;
  MuiBackdrop: BackdropProps;
  MuiBadge: BadgeProps;
  MuiBottomNavigation: BottomNavigationProps;
  MuiBottomNavigationAction: BottomNavigationActionProps;
  MuiButton: ButtonProps;
  MuiButtonBase: ButtonBaseProps;
  MuiCard: CardProps;
  MuiCardActions: CardActionsProps;
  MuiCardContent: CardContentProps;
  MuiCardHeader: CardHeaderProps;
  MuiCardMedia: CardMediaProps;
  MuiCheckbox: CheckboxProps;
  MuiChip: ChipProps;
  MuiCircularProgress: CircularProgressProps;
  MuiCollapse: CollapseProps;
  MuiCssBaseline: CssBaselineProps;
  MuiDialog: DialogProps;
  MuiDialogActions: DialogActionsProps;
  MuiDialogContent: DialogContentProps;
  MuiDialogContentText: DialogContentTextProps;
  MuiDialogTitle: DialogTitleProps;
  MuiDivider: DividerProps;
  MuiDrawer: DrawerProps;
  MuiExpansionPanel: ExpansionPanelProps;
  MuiExpansionPanelActions: ExpansionPanelActionsProps;
  MuiExpansionPanelDetails: ExpansionPanelDetailsProps;
  MuiExpansionPanelSummary: ExpansionPanelSummaryProps;
  MuiFormControl: FormControlProps;
  MuiFormControlLabel: FormControlLabelProps;
  MuiFormGroup: FormGroupProps;
  MuiFormHelperText: FormHelperTextProps;
  MuiFormLabel: FormLabelProps;
  MuiGrid: GridProps;
  MuiGridList: GridListProps;
  MuiGridListTile: GridListTileProps;
  MuiGridListTileBar: GridListTileBarProps;
  MuiIcon: IconProps;
  MuiIconButton: IconButtonProps;
  MuiInput: InputProps;
  MuiInputAdornment: InputAdornmentProps;
  MuiInputLabel: InputLabelProps;
  MuiLinearProgress: LinearProgressProps;
  MuiList: ListProps;
  MuiListItem: ListItemProps;
  MuiListItemAvatar: ListItemAvatarProps;
  MuiListItemIcon: ListItemIconProps;
  MuiListItemSecondaryAction: ListItemSecondaryActionProps;
  MuiListItemText: ListItemTextProps;
  MuiListSubheader: ListSubheaderProps;
  MuiMenu: MenuProps;
  MuiMenuItem: MenuItemProps;
  MuiMobileStepper: MobileStepperProps;
  MuiModal: ModalProps;
  MuiNativeSelect: NativeSelectProps;
  MuiPaper: PaperProps;
  MuiPopover: PopoverProps;
  MuiRadio: RadioProps;
  MuiSelect: SelectProps;
  MuiSnackbar: SnackbarProps;
  MuiSnackbarContent: SnackbarContentProps;
  MuiStep: StepProps;
  MuiStepButton: StepButtonProps;
  MuiStepConnector: StepConnectorProps;
  MuiStepContent: StepContentProps;
  MuiStepIcon: StepIconProps;
  MuiStepLabel: StepLabelProps;
  MuiStepper: StepperProps;
  MuiSvgIcon: SvgIconProps;
  MuiSwitch: SwitchProps;
  MuiSwitchBase: SwitchBaseProps;
  MuiTab: TabProps;
  MuiTable: TableProps;
  MuiTableCell: TableCellProps;
  MuiTablePagination: TablePaginationProps;
  MuiTableRow: TableRowProps;
  MuiTableSortLabel: TableSortLabelProps;
  MuiTabs: TabsProps;
  MuiToolbar: ToolbarProps;
  MuiTooltip: TooltipProps;
  MuiTouchRipple: TouchRippleProps;
  MuiTypography: TypographyProps;
};
