//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v1.5.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------


import Component from 'reactxx-mui-web/Modal/ModalManager'

export * from 'reactxx-mui-web/Modal/ModalManager'
export default Component
