//autogenerated--------------------------------------------------------------------
// 
// This code was generated from material-ui v3.0.0 by reactxx-codemod tool
// (https://github.com/reactxx/reactxx/tree/master/codemod)
// 
//----------------------------------------------------------------------------------

import React from 'react';
import PropTypes from 'prop-types';
import withStylesCreator from 'reactxx-mui-web/styles/withStyles';
import LinearProgress from 'reactxx-mui-web/LinearProgress/LinearProgress';
const styles = {
  root: {
    flexGrow: 1
  }
};

class LinearDeterminate extends React.Component<any, any> {
  timer = null;
  state: any = {
    completed: 0
  };

  componentDidMount() {
    this.timer = setInterval(this.progress, 500);
  }

  componentWillUnmount() {
    clearInterval(this.timer);
  }

  progress = () => {
    const {
      completed
    } = this.state;

    if (completed === 100) {
      this.setState({
        completed: 0
      });
    } else {
      const diff = Math.random() * 10;
      this.setState({
        completed: Math.min(completed + diff, 100)
      });
    }
  };

  render() {
    const {
      classes
    } = this.props;
    return <div className={classes.root}>
        <LinearProgress variant="determinate" value={this.state.completed} />
        <br />
        <LinearProgress color="secondary" variant="determinate" value={this.state.completed} />
      </div>;
  }

}

LinearDeterminate['propTypes'] = {
  classes: PropTypes.object.isRequired
};
export default withStylesCreator((styles as any), LinearDeterminate)();